name: Build APK

on:
  push:
    branches:
      - main  # main branch'ine push yapıldığında tetiklenir
  pull_request:
    branches:
      - main  # main branch'ine PR açıldığında tetiklenir

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Android projeniz için uygun Java sürümünü seçin
          distribution: 'temurin'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleDebug  # Debug APK oluşturur

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk